### ISSUE TITLE
请补充解题算法参考来源

### ISSUE THREAD

**Issue by NB-Dragon** [AdamYoung1234/SheepASheepV2#11]
这边通过查阅你的代码内容及提交记录，发现代码中的解题思路来自于[SheepSolver](https://github.com/NB-Dragon/SheepSolver) 。
根据AGPL-V3的开源协议，请及时在项目明显位置披露解题算法来源，例如：README.md，感谢配合

**Comment by AdamYoung1234** [comment]
...?

**Comment by AdamYoung1234** [comment]
你的代码带使用道具？

**Comment by AdamYoung1234** [comment]
如果你看 commit记录 以前用你的代码给你credit了，我现在换成别人的代码也要给你credit？我都不知道你commit记录咋翻的。我是不是以后用kmp用dp用backtracking都要给你一个credit?

**Comment by AdamYoung1234** [comment]
我给你加上了，别来沾边了
